//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using UnityStandardAssets.CrossPlatformInput;
using UnityStandardAssets.Utility;

namespace AssemblyCSharpfirstpass
{
	public class ObjectSelection
	{
		private GameObject _selectedObject;
		private Vector3 _selectionGlobalPoint;

		public ObjectSelection ()
		{
		}

		// ------------------------------------------------------------------------------
		public void UpdateResend()
		{
			if (!Camera.current)
				return;

			// Get ray hit
			Vector3 theRayOrigin = Camera.current.transform.position;
			Vector3 theRayDirection = Camera.current.transform.forward;
			
			RaycastHit theHit;
			Physics.Raycast (theRayOrigin, theRayDirection, out theHit, 100);

			// Get hit
			if (theHit.collider == null) {
				if (_selectedObject) {
					unhighlightObject(_selectedObject);
					_selectedObject = null;
				}
				return;
			}
			
			GameObject theHitedObject = theHit.collider.gameObject;
			
			if (_selectedObject && _selectedObject != theHitedObject) {
				unhighlightObject(_selectedObject);
			}
			_selectedObject = theHitedObject;
			_selectionGlobalPoint = selectedObject.transform.InverseTransformPoint (theHit.point);

			highlightObject(_selectedObject);

			return;
		}

		// ------------------------------------------------------------------------------
		public void highlightObject(GameObject inObject) {
			if (_selectedObject.GetComponent<Renderer>())
				_selectedObject.GetComponent<Renderer>().material.color = Color.red;
		}

		public void unhighlightObject(GameObject inObject) {
			if (_selectedObject.GetComponent<Renderer>())
				_selectedObject.GetComponent<Renderer>().material.color = Color.white;
		}

		// ------------------------------------------------------------------------------
		public GameObject selectedObject
		{
			get { return _selectedObject; }
		}

		public Vector3 selectionGlobalPoint
		{
			get { return _selectionGlobalPoint; }
		}
	}
}

