//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using UnityStandardAssets.CrossPlatformInput;
using UnityStandardAssets.Utility;

namespace AssemblyCSharpfirstpass
{
	public class PhysiclyDraggingObject
	{
		private GameObject _draggingObject;
		private Vector3 _attachingPoint;
		private float _telecineRadius;

		public PhysiclyDraggingObject ()
		{
		}

		public void UpdateResend()
		{
			if (_draggingObject != null) {
				Vector3 theWorldAttachingPoint = _draggingObject.transform.TransformPoint(_attachingPoint);
				Vector3 theRadiusPoint = Camera.main.transform.position + Camera.main.transform.forward.normalized * _telecineRadius;
				
				_draggingObject.GetComponent<Rigidbody>().AddForce(theRadiusPoint - theWorldAttachingPoint, ForceMode.Impulse);
			}
		}

		public void startDragging(GameObject inObject, Vector3 inAttachingPoint, float inRadius) {
			_draggingObject = inObject;
			_attachingPoint = inAttachingPoint;
			_telecineRadius = inRadius;
		}

		public void stopDragging() {
			_draggingObject = null;
		}
	}
}

